# ! Refer This https://geshan.com.np/blog/2023/01/nextjs-docker/----------------------------
# * Multistage Dockerfile for web 

# * Build Stage
FROM node:16-alpine AS BUILD_IMAGE
RUN mkdir -p /usr/web
WORKDIR /usr/web
COPY . .
RUN yarn install
RUN yarn run build
RUN rm -rf node_modules
RUN yarn install --production

# * Production Stage
FROM node:16-alpine
ENV NODE_ENV production
RUN mkdir -p /usr/web
WORKDIR /usr/web
COPY --from=BUILD_IMAGE /usr/web/node_modules ./node_modules
COPY --from=BUILD_IMAGE /usr/web/package.json ./
COPY --from=BUILD_IMAGE /usr/web/package.json.lock ./
COPY --from=BUILD_IMAGE /usr/web/.next ./
EXPOSE 3000
CMD ["yarn", "start"]