export type toastType = {
  type?: "success" | "warning" | "error" | "info" | "neutral";
  title?: string;
  message?: string;
  position?: "top-center" | "top-right" | "top-left" | "bottom-center" | "bottom-right" | "bottom-left";
  duration?: number;
  dismissible?: boolean;
  dismissAfter?: number;
  pauseOnHover?: boolean;
  hideProgressBar?: boolean;
  closeButton?: boolean;
  className?: string;
  style?: object;
  onClick?: () => void;
  onClose?: () => void;
  onOpen?: () => void;
  transition?: "bounce" | "slide" | "zoom";
  rtl?: boolean;
  autoClose?: boolean;
  progressClassName?: string;
  progressStyle?: object;
  draggable?: boolean;
  pauseOnFocusLoss?: boolean;
  pauseOnVisibilityChange?: boolean;
  closeOnClick?: boolean;
  newestOnTop?: boolean;
  theme?: "dark" | "light";
  icon?: string;
  iconTheme?: "outline" | "filled";
  role?: string;
  ariaLive?: string;
  ariaAtomic?: boolean;
  ariaRelevant?: string;
  containerId?: string;
  containerType?: "toast" | "portal";
  containerClassName?: string;
  containerStyle?: object;
  toastId?: string | number;
  children?: React.ReactNode;
  [key: string]: any;
};
