export const countries = [
  { value: "afghanistan", label: "Afghanistan", flag: "" },
  { value: "aland_islands", label: "Aland Islands", flag: "" },
  { value: "albania", label: "Albania", flag: "" },
  { value: "algeria", label: "Algeria", flag: "" },
  { value: "american_samoa", label: "American Samoa", flag: "" },
  { value: "andorra", label: "Andorra", flag: "" },
  { value: "angola", label: "Angola", flag: "" },
  { value: "anguilla", label: "Anguilla", flag: "" },
  { value: "antarctica", label: "Antarctica", flag: "" },
  { value: "antigua_and_barbuda", label: "Antigua and Barbuda", flag: "" },
  { value: "argentina", label: "Argentina", flag: "" },
  { value: "armenia", label: "Armenia", flag: "" },
  { value: "aruba", label: "Aruba", flag: "" },
  { value: "australia", label: "Australia", flag: "" },
  { value: "austria", label: "Austria", flag: "" },
  { value: "azerbaijan", label: "Azerbaijan", flag: "" },
  { value: "bahamas", label: "Bahamas", flag: "" },
  { value: "bahrain", label: "Bahrain", flag: "" },
  { value: "bangladesh", label: "Bangladesh", flag: "" },
  { value: "barbados", label: "Barbados", flag: "" },
  { value: "belarus", label: "Belarus", flag: "" },
  { value: "belgium", label: "Belgium", flag: "" },
  { value: "belize", label: "Belize", flag: "" },
  { value: "benin", label: "Benin", flag: "" },
  { value: "bermuda", label: "Bermuda", flag: "" },
  { value: "bhutan", label: "Bhutan", flag: "" },
  { value: "bolivia", label: "Bolivia", flag: "" },
  { value: "bonaire", label: "Bonaire", flag: "" },
  { value: "bosnia_and_herzegovina", label: "Bosnia and Herzegovina", flag: "" },
  { value: "botswana", label: "Botswana", flag: "" },
  { value: "bouvet_island", label: "Bouvet Island", flag: "" },
  { value: "brazil", label: "Brazil", flag: "" },
  { value: "brunei_darussalam", label: "Brunei Darussalam", flag: "" },
  { value: "bulgaria", label: "Bulgaria", flag: "" },
  { value: "burkina_faso", label: "Burkina Faso", flag: "" },
  { value: "burundi", label: "Burundi", flag: "" },
  { value: "cabo_verde", label: "Cabo Verde", flag: "" },
  { value: "cambodia", label: "Cambodia", flag: "" },
  { value: "cameroon", label: "Cameroon", flag: "" },
  { value: "canada", label: "Canada", flag: "" },
  { value: "cayman_islands", label: "Cayman Islands", flag: "" },
  { value: "central_african_republic", label: "Central African Republic", flag: "" },
  { value: "chad", label: "Chad", flag: "" },
  { value: "chile", label: "Chile", flag: "" },
  { value: "china", label: "China", flag: "" },
  { value: "christmas_island", label: "Christmas Island", flag: "" },
  { value: "cocos_islands", label: "Cocos Islands", flag: "" },
  { value: "colombia", label: "Colombia", flag: "" },
  { value: "comoros", label: "Comoros", flag: "" },
  { value: "congo", label: "Congo", flag: "" },
  { value: "cook_islands", label: "Cook Islands", flag: "" },
  { value: "costa_rica", label: "Costa Rica", flag: "" },
  { value: "cote_d'ivoire", label: "Cote d'Ivoire", flag: "" },
  { value: "croatia", label: "Croatia", flag: "" },
  { value: "cuba", label: "Cuba", flag: "" },
  { value: "curacao", label: "Curacao", flag: "" },
  { value: "cyprus", label: "Cyprus", flag: "" },
  { value: "czech_republic", label: "Czech Republic", flag: "" },
  { value: "denmark", label: "Denmark", flag: "" },
  { value: "djibouti", label: "Djibouti", flag: "" },
  { value: "dominica", label: "Dominica", flag: "" },
  { value: "dominican_republic", label: "Dominican Republic", flag: "" },
  { value: "ecuador", label: "Ecuador", flag: "" },
  { value: "egypt", label: "Egypt", flag: "" },
  { value: "el_salvador", label: "El Salvador", flag: "" },
  { value: "equatorial_guinea", label: "Equatorial Guinea", flag: "" },
  { value: "eritrea", label: "Eritrea", flag: "" },
  { value: "estonia", label: "Estonia", flag: "" },
  { value: "ethiopia", label: "Ethiopia", flag: "" },
  { value: "falkland_islands", label: "Falkland Islands", flag: "" },
  { value: "faroe_islands", label: "Faroe Islands", flag: "" },
  { value: "fiji", label: "Fiji", flag: "" },
  { value: "finland", label: "Finland", flag: "" },
  { value: "france", label: "France", flag: "" },
  { value: "french_guiana", label: "French Guiana", flag: "" },
  { value: "french_polynesia", label: "French Polynesia", flag: "" },
  { value: "french_southern_territories", label: "French Southern Territories", flag: "" },
  { value: "gabon", label: "Gabon", flag: "" },
  { value: "gambia", label: "Gambia", flag: "" },
  { value: "georgia", label: "Georgia", flag: "" },
  { value: "germany", label: "Germany", flag: "" },
  { value: "ghana", label: "Ghana", flag: "" },
  { value: "gibraltar", label: "Gibraltar", flag: "" },
  { value: "greece", label: "Greece", flag: "" },
  { value: "greenland", label: "Greenland", flag: "" },
  { value: "grenada", label: "Grenada", flag: "" },
  { value: "guadeloupe", label: "Guadeloupe", flag: "" },
  { value: "guam", label: "Guam", flag: "" },
  { value: "guatemala", label: "Guatemala", flag: "" },
  { value: "guernsey", label: "Guernsey", flag: "" },
  { value: "guinea", label: "Guinea", flag: "" },
  { value: "guinea-bissau", label: "Guinea-Bissau", flag: "" },
  { value: "guyana", label: "Guyana", flag: "" },
  { value: "haiti", label: "Haiti", flag: "" },
  { value: "heard_and_mcdonald_islands", label: "Heard and McDonald Islands", flag: "" },
  { value: "holy_see", label: "Holy See", flag: "" },
  { value: "honduras", label: "Honduras", flag: "" },
  { value: "hong_kong", label: "Hong Kong", flag: "" },
  { value: "hungary", label: "Hungary", flag: "" },
  { value: "iceland", label: "Iceland", flag: "" },
  { value: "india", label: "🇮🇳 India", flag: "🇮🇳" },
  { value: "indonesia", label: "Indonesia", flag: "" },
  { value: "iran", label: "Iran", flag: "" },
  { value: "iraq", label: "Iraq", flag: "" },
  { value: "ireland", label: "Ireland", flag: "" },
  { value: "isle_of_man", label: "Isle of Man", flag: "" },
  { value: "israel", label: "Israel", flag: "" },
  { value: "italy", label: "Italy", flag: "" },
  { value: "jamaica", label: "Jamaica", flag: "" },
  { value: "japan", label: "Japan", flag: "" },
  { value: "jersey", label: "Jersey", flag: "" },
  { value: "jordan", label: "Jordan", flag: "" },
  { value: "kazakhstan", label: "Kazakhstan", flag: "" },
  { value: "kenya", label: "Kenya", flag: "" },
  { value: "kiribati", label: "Kiribati", flag: "" },
  { value: "korea", label: "Korea", flag: "" },
  { value: "kuwait", label: "Kuwait", flag: "" },
  { value: "kyrgyzstan", label: "Kyrgyzstan", flag: "" },
  { value: "lao_peoples", label: "Lao People's", flag: "" },
  { value: "latvia", label: "Latvia", flag: "" },
  { value: "lebanon", label: "Lebanon", flag: "" },
  { value: "lesotho", label: "Lesotho", flag: "" },
  { value: "liberia", label: "Liberia", flag: "" },
  { value: "libya", label: "Libya", flag: "" },
  { value: "liechtenstein", label: "Liechtenstein", flag: "" },
  { value: "lithuania", label: "Lithuania", flag: "" },
  { value: "luxembourg", label: "Luxembourg", flag: "" },
  { value: "macao", label: "Macao", flag: "" },
  { value: "macedonia", label: "Macedonia", flag: "" },
  { value: "madagascar", label: "Madagascar", flag: "" },
  { value: "malawi", label: "Malawi", flag: "" },
  { value: "malaysia", label: "Malaysia", flag: "" },
  { value: "maldives", label: "Maldives", flag: "" },
  { value: "mali", label: "Mali", flag: "" },
  { value: "malta", label: "Malta", flag: "" },
  { value: "marshall_islands", label: "Marshall Islands", flag: "" },
  { value: "martinique", label: "Martinique", flag: "" },
  { value: "mauritania", label: "Mauritania", flag: "" },
  { value: "mauritius", label: "Mauritius", flag: "" },
  { value: "mayotte", label: "Mayotte", flag: "" },
  { value: "mexico", label: "Mexico", flag: "" },
  { value: "micronesia", label: "Micronesia", flag: "" },
  { value: "moldova", label: "Moldova", flag: "" },
  { value: "monaco", label: "Monaco", flag: "" },
  { value: "mongolia", label: "Mongolia", flag: "" },
  { value: "montenegro", label: "Montenegro", flag: "" },
  { value: "montserrat", label: "Montserrat", flag: "" },
  { value: "morocco", label: "Morocco", flag: "" },
  { value: "mozambique", label: "Mozambique", flag: "" },
  { value: "myanmar", label: "Myanmar", flag: "" },
  { value: "namibia", label: "Namibia", flag: "" },
  { value: "nauru", label: "Nauru", flag: "" },
  { value: "nepal", label: "Nepal", flag: "" },
  { value: "netherlands", label: "Netherlands", flag: "" },
  { value: "new_caledonia", label: "New Caledonia", flag: "" },
  { value: "new_zealand", label: "New Zealand", flag: "" },
  { value: "nicaragua", label: "Nicaragua", flag: "" },
  { value: "niger", label: "Niger", flag: "" },
  { value: "nigeria", label: "Nigeria", flag: "" },
  { value: "niue", label: "Niue", flag: "" },
  { value: "norfolk_island", label: "Norfolk Island", flag: "" },
  { value: "northern_mariana_islands", label: "Northern Mariana Islands", flag: "" },
  { value: "norway", label: "Norway", flag: "" },
  { value: "oman", label: "Oman", flag: "" },
  { value: "pakistan", label: "Pakistan", flag: "" },
  { value: "palau", label: "Palau", flag: "" },
  { value: "palestine", label: "Palestine", flag: "" },
  { value: "panama", label: "Panama", flag: "" },
  { value: "papua_new_guinea", label: "Papua New Guinea", flag: "" },
  { value: "paraguay", label: "Paraguay", flag: "" },
  { value: "peru", label: "Peru", flag: "" },
  { value: "philippines", label: "Philippines", flag: "" },
  { value: "pitcairn", label: "Pitcairn", flag: "" },
  { value: "poland", label: "Poland", flag: "" },
  { value: "portugal", label: "Portugal", flag: "" },
  { value: "puerto_rico", label: "Puerto Rico", flag: "" },
  { value: "qatar", label: "Qatar", flag: "" },
  { value: "reunion", label: "Reunion", flag: "" },
  { value: "remote", label: "Remote", flag: "" },
  { value: "romania", label: "Romania", flag: "" },
  { value: "russian_federation", label: "Russian Federation", flag: "" },
  { value: "rwanda", label: "Rwanda", flag: "" },
  { value: "saint_barthelemy", label: "Saint Barthelemy", flag: "" },
  { value: "saint_helena", label: "Saint Helena", flag: "" },
  { value: "saint_kitts_and_nevis", label: "Saint Kitts and Nevis", flag: "" },
  { value: "saint_lucia", label: "Saint Lucia", flag: "" },
  { value: "saint_martin", label: "Saint Martin", flag: "" },
  { value: "saint_pierre_and_miquelon", label: "Saint Pierre and Miquelon", flag: "" },
  { value: "saint_vincent_and_the_grenadines", label: "Saint Vincent and the Grenadines", flag: "" },
  { value: "samoa", label: "Samoa", flag: "" },
  { value: "san_marino", label: "San Marino", flag: "" },
  { value: "sao_tome_and_principe", label: "Sao Tome and Principe", flag: "" },
  { value: "saudi_arabia", label: "Saudi Arabia", flag: "" },
  { value: "senegal", label: "Senegal", flag: "" },
  { value: "serbia", label: "Serbia", flag: "" },
  { value: "seychelles", label: "Seychelles", flag: "" },
  { value: "sierra_leone", label: "Sierra Leone", flag: "" },
  { value: "singapore", label: "Singapore", flag: "" },
  { value: "sint_maarten", label: "Sint Maarten", flag: "" },
  { value: "slovakia", label: "Slovakia", flag: "" },
  { value: "slovenia", label: "Slovenia", flag: "" },
  { value: "solomon_islands", label: "Solomon Islands", flag: "" },
  { value: "somalia", label: "Somalia", flag: "" },
  { value: "south_africa", label: "South Africa", flag: "" },
  { value: "south_georgia", label: "South Georgia", flag: "" },
  { value: "south_sudan", label: "South Sudan", flag: "" },
  { value: "spain", label: "Spain", flag: "" },
  { value: "sri_lanka", label: "Sri Lanka", flag: "" },
  { value: "sudan", label: "Sudan", flag: "" },
  { value: "suriname", label: "Suriname", flag: "" },
  { value: "svalbard_and_jan mayen", label: "Svalbard and Jan Mayen", flag: "" },
  { value: "swaziland", label: "Swaziland", flag: "" },
  { value: "sweden", label: "Sweden", flag: "" },
  { value: "switzerland", label: "Switzerland", flag: "" },
  { value: "syrian_arab_republic", label: "Syrian Arab Republic", flag: "" },
  { value: "taiwan", label: "Taiwan", flag: "" },
  { value: "tajikistan", label: "Tajikistan", flag: "" },
  { value: "tanzania", label: "Tanzania", flag: "" },
  { value: "thailand", label: "Thailand", flag: "" },
  { value: "timor_leste", label: "Timor Leste", flag: "" },
  { value: "togo", label: "Togo", flag: "" },
  { value: "tokelau", label: "Tokelau", flag: "" },
  { value: "tonga", label: "Tonga", flag: "" },
  { value: "trinidad_and_tobago", label: "Trinidad and Tobago", flag: "" },
  { value: "tunisia", label: "Tunisia", flag: "" },
  { value: "turvalue", label: "Turvalue", flag: "" },
  { value: "turkmenistan", label: "Turkmenistan", flag: "" },
  { value: "turks_and_caicos islands", label: "Turks and Caicos Islands", flag: "" },
  { value: "tuvalu", label: "Tuvalu", flag: "" },
  { value: "uganda", label: "Uganda", flag: "" },
  { value: "ukraine", label: "Ukraine", flag: "" },
  { value: "united_arab_emirates", label: "United Arab Emirates", flag: "" },
  { value: "united_kingdom", label: "United Kingdom", flag: "" },
  { value: "united_states_of america", label: "United States of America", flag: "" },
  { value: "uruguay", label: "Uruguay", flag: "" },
  { value: "uzbekistan", label: "Uzbekistan", flag: "" },
  { value: "vanuatu", label: "Vanuatu", flag: "" },
  { value: "venezuela", label: "Venezuela", flag: "" },
  { value: "viet_nam", label: "Viet Nam", flag: "" },
  { value: "virgin_islands", label: "Virgin Islands", flag: "" },
  { value: "wallis_and_futuna", label: "Wallis and Futuna", flag: "" },
  { value: "western_sahara", label: "Western Sahara", flag: "" },
  { value: "yemen", label: "Yemen", flag: "" },
  { value: "zambia", label: "Zambia", flag: "" },
  { value: "zimbabwe", label: "Zimbabwe", flag: "" },
];
