export const currencies = [
  { label: "United States Dollar ( $ )", value: "$" },
  { label: "Euro ( € )", value: "€" },
  { label: "British Pound Sterling ( £ )", value: "£" },
  { label: "Japanese Yen ( ¥ )", value: "¥" },
  { label: "Australian Dollar ( A$ )", value: "A$" },
  { label: "Canadian Dollar ( C$ )", value: "C$" },
  { label: "Swiss Franc ( Fr. )", value: "Fr." },
  { label: "Chinese Yuan Renminbi ( ¥ )", value: "¥" },
  { label: "Indian Rupee ( ₹ )", value: "₹" },
  { label: "South Korean Won ( ₩ )", value: "₩" },
  { label: "Russian Ruble ( ₽ )", value: "₽" },
  { label: "Brazilian Real ( R$ )", value: "R$" },
  { label: "Mexican Peso ( $ )", value: "$" },
  { label: "South African Rand ( R )", value: "R" },
  { label: "Singapore Dollar ( S$ )", value: "S$" },
  { label: "Hong Kong Dollar ( HK$ )", value: "HK$" },
  { label: "New Zealand Dollar ( NZ$ )", value: "NZ$" },
  { label: "Swedish Krona ( kr )", value: "kr" },
  { label: "Norwegian Krone ( kr )", value: "kr" },
  { label: "Danish Krone ( kr )", value: "kr" },
  { label: "Turkish Lira ( ₺ )", value: "₺" },
  { label: "Indonesian Rupiah ( Rp )", value: "Rp" },
  { label: "Thai Baht ( ฿ )", value: "฿" },
  { label: "Malaysian Ringgit ( RM )", value: "RM" },
  { label: "Philippine Peso ( ₱ )", value: "₱" },
  { label: "Pakistani Rupee ( ₨ )", value: "₨" },
  { label: "Vietnamese Dong ( ₫ )", value: "₫" },
  { label: "Saudi Riyal ( ر.س )", value: "ر.س" },
  { label: "United Arab Emirates Dirham ( د.إ )", value: "د.إ" },
  { label: "Egyptian Pound ( £ )", value: "£" },
  { label: "Qatari Riyal ( ر.ق )", value: "ر.ق" },
  { label: "Kuwaiti Dinar ( د.ك )", value: "د.ك" },
  { label: "Omani Rial ( ر.ع. )", value: "ر.ع." },
  { label: "Israeli Shekel ( ₪ )", value: "₪" },
  { label: "Polish Zloty ( zł )", value: "zł" },
  { label: "Czech Koruna ( Kč )", value: "Kč" },
  { label: "Hungarian Forint ( Ft )", value: "Ft" },
  { label: "Romanian Leu ( L )", value: "L" },
  { label: "Bulgarian Lev ( лв. )", value: "лв." },
  { label: "Croatian Kuna ( kn )", value: "kn" },
  { label: "Icelandic Krona ( kr )", value: "kr" },
  { label: "Ukrainian Hryvnia ( ₴ )", value: "₴" },
  { label: "Argentine Peso ( $ )", value: "$" },
  { label: "Chilean Peso ( $ )", value: "$" },
  { label: "Peruvian Sol ( S/ )", value: "S/" },
  { label: "Colombian Peso ( $ )", value: "$" },
  { label: "Venezuelan Bolívar ( Bs. )", value: "Bs." },
  { label: "Ghanaian Cedi ( ₵ )", value: "₵" },
  { label: "Nigerian Naira ( ₦ )", value: "₦" },
  { label: "Kenyan Shilling ( Sh )", value: "Sh" },
  { label: "Tanzanian Shilling ( Sh )", value: "Sh" },
  { label: "Ugandan Shilling ( Sh )", value: "Sh" },
  { label: "Ethiopian Birr ( Br )", value: "Br" },
  { label: "Moroccan Dirham ( د.م. )", value: "د.م." },
  { label: "Tunisian Dinar ( د.ت )", value: "د.ت" },
  { label: "Jordanian Dinar ( د.ا )", value: "د.ا" },
  { label: "Bahraini Dinar ( ب.د )", value: "ب.د" },
  { label: "Sri Lankan Rupee ( Rs )", value: "Rs" },
  { label: "Bangladeshi Taka ( ৳ )", value: "৳" },
  { label: "Nepalese Rupee ( रू )", value: "रू" },
  { label: "Afghan Afghani ( ؋ )", value: "؋" },
  { label: "Iranian Rial ( ﷼ )", value: "﷼" },
  { label: "Iraqi Dinar ( د.ع )", value: "د.ع" },
  { label: "Lebanese Pound ( ل.ل )", value: "ل.ل" },
  { label: "Syrian Pound ( £S )", value: "£S" },
  { label: "Myanmar Kyat ( K )", value: "K" },
  { label: "Cambodian Riel ( ៛ )", value: "៛" },
  { label: "Laotian Kip ( ₭ )", value: "₭" },
  { label: "Mongolian Tugrik ( ₮ )", value: "₮" },
  { label: "Kazakhstani Tenge ( ₸ )", value: "₸" },
  { label: "Uzbekistani Som ( soʻm )", value: "soʻm" },
  { label: "Turkmenistan Manat ( m )", value: "m" },
  { label: "Georgian Lari ( ₾ )", value: "₾" },
  { label: "Armenian Dram ( ֏ )", value: "֏" },
  { label: "Azerbaijani Manat ( ₼ )", value: "₼" },
  { label: "Belarusian Ruble ( Br )", value: "Br" },
  { label: "Serbian Dinar ( дин )", value: "дин" },
  { label: "Macedonian Denar ( ден )", value: "ден" },
  { label: "Bosnia and Herzegovina Convertible Mark ( KM )", value: "KM" },
  { label: "Albanian Lek ( L )", value: "L" },
  { label: "Moldovan Leu ( L )", value: "L" },
  { label: "Maldivian Rufiyaa ( ރ. )", value: "ރ." },
  { label: "Mauritian Rupee ( Rs )", value: "Rs" },
  { label: "Seychellois Rupee ( ₨ )", value: "₨" },
  { label: "Fijian Dollar ( $ )", value: "$" },
  { label: "Papua New Guinean Kina ( K )", value: "K" },
  { label: "Samoan Tala ( T )", value: "T" },
  { label: "Tongan Paʻanga ( T$ )", value: "T$" },
  { label: "Vanuatu Vatu ( VT )", value: "VT" },
  { label: "Solomon Islands Dollar ( $ )", value: "$" },
  { label: "East Caribbean Dollar ( EC$ )", value: "EC$" },
  { label: "Barbadian Dollar ( $ )", value: "$" },
  { label: "Bahamian Dollar ( $ )", value: "$" },
  { label: "Jamaican Dollar ( J$ )", value: "J$" },
  { label: "Trinidad and Tobago Dollar ( TT$ )", value: "TT$" },
  { label: "Haitian Gourde ( G )", value: "G" },
  { label: "Dominican Peso ( RD$ )", value: "RD$" },
  { label: "Cuban Peso ( $ )", value: "$" },
  { label: "Panamanian Balboa ( B/. )", value: "B/." },
  { label: "Costa Rican Colón ( ₡ )", value: "₡" },
  { label: "Honduran Lempira ( L )", value: "L" },
  { label: "Nicaraguan Córdoba ( C$ )", value: "C$" },
  { label: "Guatemalan Quetzal ( Q )", value: "Q" },
  { label: "El Salvadoran Colón ( ₡ )", value: "₡" },
  { label: "Belize Dollar ( BZ$ )", value: "BZ$" },
];
