import { SubscriptionPlan } from "@/types";

export const plans: SubscriptionPlan[] = [
  {
    name: "Basic plan",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: "Free",
    isMostPop: false,
    features: [
      "Curabitur faucibus",
      "massa ut pretium maximus",
      "Sed posuere nisi",
      "Pellentesque eu nibh et neque",
      "Suspendisse a leo",
      "Praesent quis venenatis ipsum",
      "Duis non diam vel tortor",
      "Curabitur faucibus",
      "massa ut pretium maximus",
      "Sed posuere nisi",
      "Pellentesque eu nibh et neque",
      "Suspendisse a leo",
      "Praesent quis venenatis ipsum",
      "Duis non diam vel tortor",
    ],
    stripePriceId: "",
  },
  {
    name: "Startup",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 35,
    isMostPop: true,
    features: [
      "Curabitur faucibus",
      "massa ut pretium maximus",
      "Sed posuere nisi",
      "Pellentesque eu nibh et neque",
      "Suspendisse a leo",
      "Praesent quis venenatis ipsum",
      "Duis non diam vel tortor",
      "Curabitur faucibus",
      "massa ut pretium maximus",
      "Sed posuere nisi",
      "Pellentesque eu nibh et neque",
      "Suspendisse a leo",
      "Praesent quis venenatis ipsum",
      "Duis non diam vel tortor",
    ],
    stripePriceId: "",
  },
  {
    name: "Enterprise",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 60,
    isMostPop: false,
    features: [
      "Curabitur faucibus",
      "massa ut pretium maximus",
      "Sed posuere nisi",
      "Pellentesque eu nibh et neque",
      "Suspendisse a leo",
      "Praesent quis venenatis ipsum",
      "Duis non diam vel tortor",
      "Curabitur faucibus",
      "massa ut pretium maximus",
      "Sed posuere nisi",
      "Pellentesque eu nibh et neque",
      "Suspendisse a leo",
      "Praesent quis venenatis ipsum",
      "Duis non diam vel tortor",
    ],
    stripePriceId: "",
  },
];

// stripePriceId: process.env.STRIPE_PRO_MONTHLY_PLAN_ID || "",
