const jobTypeListObj = [
  "Full Time",
  "Part Time",
  "Intern",
  "Temporary",
  "Contractor",
  "Volunteer",
  "Freelance",
  "Cofounder",
];

export const jobTypeList = jobTypeListObj.map((item) => ({
  value: item,
  label: item,
}));

const skills = [
  "React.js",
  "Python",
  "JavaScript",
  "TypeScript",
  "Node.js",
  "HTML5",
  "CSS3",
  "Git",
  "Docker",
  "AWS",
  "Azure",
  "Google Cloud",
  "Next.js",
  "Express.js",
  "Django",
  "Flask",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "GraphQL",
  "RESTful APIs",
  "WebSockets",
  "JSON",
  "AJAX",
  "SASS",
  "Bootstrap",
  "Material-UI",
  "Tailwind CSS",
  "Chakra UI",
  "Redux",
  "MobX",
  "RxJS",
  "Vue.js",
  "Angular",
  "Svelte",
  "PHP",
  "Laravel",
  "Symfony",
  "Ruby",
  "Ruby on Rails",
  "Go",
  "Rust",
  "Java",
  "Kotlin",
  "Swift",
  "Objective-C",
  "C",
  "C++",
  "C#",
  ".NET",
  "Spring Boot",
  "Hibernate",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "ElasticSearch",
  "Solr",
  "Jira",
  "Confluence",
  "Trello",
  "Slack",
  "VS Code",
  "IntelliJ IDEA",
  "Eclipse",
  "Xcode",
  "Unity",
  "Unreal Engine",
  "WebAssembly",
  "OpenGL",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "OpenCV",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "Apollo",
  "gRPC",
  "OAuth2",
  "JWT",
  "Microservices",
  "Service Mesh",
  "Serverless",
  "Webpack",
  "Babel",
  "Vite",
  "Parcel",
  "Turbopack",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Puppeteer",
  "Playwright",
  "Postman",
  "Figma",
  "Sketch",
  "InVision",
  "Kubernetes",
  "Docker Swarm",
  "Mesos",
  "CI/CD",
  "Prometheus",
  "Grafana",
  "Nagios",
  "New Relic",
  "AppDynamics",
  "Logstash",
  "Kibana",
  "DataDog",
  "Consul",
  "Vault",
  "HashiCorp",
  "Istio",
  "Linkerd",
  "Apache Kafka",
  "RabbitMQ",
  "ActiveMQ",
  "Zookeeper",
  "Protobuf",
  "Thrift",
  "SOAP",
  "REST API",
  "Hadoop",
  "Spark",
  "Hive",
  "Pig",
  "Flink",
  "Storm",
  "Airflow",
  "Luigi",
  "TensorFlow Lite",
  "MLflow",
  "Kubeflow",
  "ONNX",
  "Apache Mahout",
  "AutoML",
  "FastAPI",
  "Falcon",
  "Bottle",
  "Tornado",
  "WSGI",
  "Celery",
  "Pika",
  "ZeroMQ",
  "Kafka Streams",
  "Akka",
  "Play Framework",
  "Lagom",
  "Finagle",
  "Spring Security",
  "SAML",
  "OpenID Connect",
  "LDAP",
  "Keycloak",
  "Supabase",
  "Hasura",
  "WebRTC",
  "PWAs",
  "AMP",
  "NativeScript",
  "Ionic",
  "React Native",
  "Flutter",
  "Xamarin",
  "Unity3D",
  "Blender",
  "Cinema 4D",
  "Maya",
  "Autodesk 3ds Max",
  "WebGL",
  "Three.js",
  "Babylon.js",
  "Gulp",
  "Grunt",
  "Rollup",
  "ESLint",
  "Prettier",
  "TSlint",
  "Husky",
  "Lerna",
  "Nx",
  "Electron",
  "Capacitor",
  "Couchbase",
  "Firebase Firestore",
  "DynamoDB",
  "Neo4j",
  "Cassandra",
  "ArangoDB",
  "CouchDB",
  "OrientDB",
  "HBase",
  "Presto",
  "ClickHouse",
  "BigQuery",
];

export const skillsList = skills.map((item) => ({
  value: item,
  label: item,
}));

const jobRoleListObj = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Quality Assurance (QA) Engineer",
  "Business Analyst",
  "Data Engineer",
  "Machine Learning Engineer",
  "Security Engineer",
  "Embedded Systems Engineer",
  "Game Developer",
  "Software Engineer",
  "Marketing Manager",
  "Financial Analyst",
  "Graphic Designer",
  "Human Resources Specialist",
  "Sales Representative",
  "Technical Support Engineer",
  "Systems Analyst",
  "Cloud Engineer",
  "Site Reliability Engineer",
  "Mobile App Developer",
  "UI/UX Designer",
  "Data Scientist",
  "Network Engineer",
  "Database Administrator",
  "Product Manager",
  "Project Manager",
  "Research Scientist",
  "Information Security Analyst",
  "Application Developer",
  "Blockchain Developer",
  "Artificial Intelligence Engineer",
  "Web Developer",
  "API Developer",
  "IT Consultant",
  "Technical Writer",
  "Scrum Master",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Content Strategist",
  "Product Designer",
  "Business Intelligence Analyst",
  "DevSecOps Engineer",
  "Test Automation Engineer",
  "Site Administrator",
  "E-commerce Specialist",
  "Systems Architect",
  "Software Architect",
  "Technical Project Manager",
  "Data Analyst",
  "User Researcher",
  "IT Support Specialist",
  "Web Designer",
  "Game Designer",
  "Video Game Tester",
  "Cloud Solutions Architect",
  "IoT Developer",
  "Augmented Reality Developer",
  "Virtual Reality Developer",
  "Operations Manager",
  "Customer Support Engineer",
  "Technical Account Manager",
  "Change Manager",
  "IT Operations Manager",
  "Help Desk Technician",
  "Software Development Manager",
  "Sales Engineer",
  "Configuration Manager",
  "Desktop Support Technician",
  "Product Owner",
  "Compliance Analyst",
  "Release Manager",
  "Data Governance Analyst",
  "UX Researcher",
  "IT Auditor",
  "Penetration Tester",
  "Incident Response Analyst",
  "Social Media Manager",
  "Digital Product Manager",
  "Database Developer",
  "SRE Manager",
  "Content Developer",
  "Performance Engineer",
  "Game Producer",
  "SEO Manager",
  "Business Development Manager",
  "Privacy Officer",
  "IT Risk Manager",
  "Incident Manager",
  "Change Control Manager",
  "Application Support Analyst",
  "Technology Trainer",
  "Technical Sales Consultant",
  "Cloud Security Engineer",
  "Product Marketing Manager",
  "Machine Learning Researcher",
  "AI Research Scientist",
  "Data Visualization Engineer",
  "Systems Integrator",
  "Big Data Engineer",
  "IoT Solutions Architect",
  "Mobile UX Designer",
  "Web Applications Developer",
  "UI Developer",
  "Front-End Architect",
  "Back-End Architect",
  "Software Development Engineer in Test (SDET)",
  "Mobile Game Developer",
  "Software Quality Engineer",
  "Risk Analyst",
  "User Interface Engineer",
  "Lead Developer",
  "Blockchain Architect",
  "Algorithm Engineer",
  "Firmware Engineer",
  "Technical Lead",
  "Data Center Engineer",
  "SAP Consultant",
  "Cloud Infrastructure Engineer",
  "Mobile Security Engineer",
  "Telecommunications Engineer",
  "Salesforce Developer",
  "Agile Coach",
  "IT Manager",
  "Solutions Architect",
  "Application Security Engineer",
  "Supply Chain Analyst",
  "Digital Analyst",
  "Web Optimization Specialist",
  "Capacity Planner",
  "Business Systems Analyst",
  "IT Procurement Specialist",
  "Customer Success Manager",
  "Technical Program Manager",
  "Service Desk Analyst",
  "Client Solutions Consultant",
  "Identity and Access Management Analyst",
  "Virtualization Engineer",
  "Data Privacy Officer",
  "Backup and Recovery Specialist",
  "Middleware Developer",
  "Digital Content Manager",
  "User Experience Architect",
  "Technical Operations Engineer",
  "Risk and Compliance Manager",
  "Database Analyst",
  "Integration Developer",
  "Data Warehouse Developer",
  "Product Analyst",
  "Embedded Software Engineer",
  "E-learning Developer",
  "Robotics Engineer",
  "IT Change Manager",
  "User Interface Designer",
  "Cybersecurity Analyst",
  "Quality Control Engineer",
  "Lead Software Engineer",
  "Network Security Engineer",
  "Financial Software Developer",
  "Mobile App Tester",
  "Technical Program Director",
  "Product Support Specialist",
  "IT Compliance Manager",
  "Digital Transformation Consultant",
  "Data Strategy Consultant",
  "Game Director",
  "Online Community Manager",
  "Ethical Hacker",
  "Information Systems Manager",
  "Software Deployment Engineer",
  "Process Improvement Specialist",
  "Network Operations Center (NOC) Engineer",
  "Site Reliability Manager",
  "Software Quality Analyst",
  "Data Migration Specialist",
  "Web Content Manager",
  "IT Systems Manager",
  "E-commerce Developer",
  "User Experience Designer",
  "Java Developer",
  "Python Developer",
  "C# Developer",
  "PHP Developer",
  "Ruby Developer",
  "Swift Developer",
  "Kotlin Developer",
  "Scala Developer",
  "Go Developer",
  "C++ Developer",
];

export const jobRoleList = jobRoleListObj.map((item) => ({
  value: item,
  label: item,
}));

const oldexperienceListObj = [
  "Internship",
  "Entry-level",
  "Associate",
  "Mid-level",
  "Senior",
  "Manager",
  "Director",
  "Executive",
];

const companyListObj = [
  "Google",
  "Microsoft",
  "Apple",
  "Amazon",
  "Facebook",
  "Netflix",
  "Tesla",
  "Twitter",
  "IBM",
  "Oracle",
  "Adobe",
  "Salesforce",
  "Intel",
  "Uber",
  "Airbnb",
  "Spotify",
  "Dropbox",
  "Slack",
  "Zoom",
  "Pinterest",
  "Shopify",
  "Stripe",
  "Square",
  "PayPal",
  "GitHub",
  "Atlassian",
  "LinkedIn",
  "Red Hat",
  "Cisco",
  "SAP",
  "Nvidia",
  "VMware",
  "Dell",
  "HP",
  "Meta",
  "Samsung",
  "Tencent",
  "ByteDance",
  "Alibaba",
  "Baidu",
  "Huawei",
  "JD.com",
  "Cloudflare",
  "Snowflake",
  "Datadog",
  "Splunk",
  "Asana",
  "Miro",
  "Figma",
  "ZoomInfo",
  "Elastic",
  "MongoDB",
  "DigitalOcean",
  "Squarespace",
  "Weebly",
  "GitLab",
  "Trello",
  "HubSpot",
  "ServiceNow",
  "Twilio",
  "SendGrid",
  "Okta",
  "Workday",
  "Dropbox",
  "Confluent",
  "Palantir",
  "Epic Games",
  "Unity Technologies",
  "Electronic Arts",
  "Valve",
  "Riot Games",
  "Slack",
  "Zoom Video",
  "Coinbase",
  "Robinhood",
  "Plaid",
  "Stripe",
  "Klarna",
  "Wise",
  "Zillow",
  "DoorDash",
  "Instacart",
  "Peloton",
  "Squarespace",
  "Roblox",
  "Pinterest",
  "Hulu",
  "Coursera",
  "Duolingo",
  "Grammarly",
  "Notion",
  "Canva",
  "Zapier",
  "Twitch",
  "Bolt",
  "Grab",
  "Coupang",
  "Flipkart",
  "Zomato",
  "Ola",
  "Swiggy",
  "MakeMyTrip",
  "BYJU's",
  "CRED",
  "Glovo",
  "Gojek",
  "Revolut",
  "Mambu",
  "TransferWise",
  "Freshworks",
  "Pivotal",
  "Segment",
  "Algolia",
  "Elastic",
  "Nutanix",
  "CrowdStrike",
  "AppLovin",
  "Toast",
  "Toast POS",
  "HashiCorp",
  "PagerDuty",
  "DocuSign",
  "GitKraken",
  "Heroku",
  "DigitalOcean",
  "Namecheap",
  "GoDaddy",
  "Cloudflare",
  "Fastly",
  "Netlify",
  "Vercel",
  "Weaviate",
  "Turing",
  "Clever",
  "TopTal",
  "Triplebyte",
  "Andela",
  "Crossover",
  "Upwork",
  "Fiverr",
  "HackerRank",
  "Leetcode",
  "CodeSignal",
  "InterviewBit",
  "Codility",
  "Glitch",
  "CodePen",
  "JSFiddle",
  "JSBin",
  "Repl.it",
  "CodeSandbox",
  "StackBlitz",
  "Etsy",
  "Mercari",
  "Poshmark",
  "ThredUp",
  "Depop",
  "GitBook",
  "RedwoodJS",
  "Superbase",
  "Sanity",
  "Contentful",
  "Prismic",
  "Ghost",
  "Wix",
  "WordPress",
  "Weebly",
  "Joomla",
  "Magento",
  "BigCommerce",
  "Shopify",
  "Lightspeed",
  "PrestaShop",
  "OpenCart",
  "BigCartel",
  "Square",
  "Fiverr",
  "Upwork",
  "Toptal",
  "Crossover",
  "Flexport",
  "Patreon",
  "Substack",
  "Medium",
  "WordPress.com",
  "Typeform",
  "SurveyMonkey",
  "Qualtrics",
  "SoFi",
  "Robinhood",
  "Betterment",
  "Lemonade",
  "Oscar Health",
  "Policygenius",
  "Chime",
  "Brex",
  "Plaid",
  "Affirm",
  "SoFi",
  "Credit Karma",
  "LendingClub",
  "NerdWallet",
  "ClearScore",
  "Kabbage",
  "Robinhood",
  "OpenSea",
  "Rarible",
  "Solana Labs",
  "Chainalysis",
  "BlockFi",
  "Gemini",
  "Kraken",
  "BitPay",
  "Blockchain.com",
  "Bitwise",
  "Ripple",
  "Anchorage",
  "Consensys",
  "Alchemy",
  "OpenNode",
  "Immutable",
  "Infura",
  "MetaMask",
  "Trust Wallet",
  "Ledger",
  "Trezor",
  "Coinomi",
  "Exodus",
  "Electrum",
  "Mycelium",
  "Wasabi Wallet",
  "Samourai Wallet",
  "Edge Wallet",
  "Atomic Wallet",
  "Cake Wallet",
];
export const companyList = companyListObj.map((item) => ({
  value: item,
  label: item,
}));

export const accept = [
  {
    id: "shortMessage",
    label: "Short Message",
  },
] as const;

export const pdfs = [
  {
    id: "resume",
    label: "Resume",
  },
  {
    id: "coverLetter",
    label: "Cover Letter",
  },
] as const;

export const links = [
  {
    id: "linkedin",
    label: "LinkedIn",
  },
  {
    id: "github",
    label: "GitHub",
  },
  {
    id: "portfolio",
    label: "Portfolio",
  },
  {
    id: "medium",
    label: "Medium",
  },
  {
    id: "twitter",
    label: "Twitter",
  },
  {
    id: "dribbble",
    label: "Dribbble",
  },
] as const;

export const postType = [
  {
    id: "Referral Post",
    label: "Referral Post",
  },
  {
    id: "Seek Referral",
    label: "Seek Referral",
  },
  {
    id: "Post",
    label: "Post",
  },
] as const;

export const jobLoationType = [
  {
    id: "On-Site",
    label: "On-Site",
  },
  {
    id: "Remote",
    label: "Remote",
  },
  {
    id: "Hybrid",
    label: "Hybrid",
  },
  {
    id: "Remote Only",
    label: "Remote Only",
  },
] as const;

const currencies = [
  "United States Dollar ($)",
  "Euro (€)",
  "British Pound Sterling (£)",
  "Japanese Yen (¥)",
  "Australian Dollar (A$)",
  "Canadian Dollar (C$)",
  "Swiss Franc (Fr.)",
  "Chinese Yuan Renminbi (¥)",
  "Indian Rupee (₹)",
  "South Korean Won (₩)",
  "Russian Ruble (₽)",
  "Brazilian Real (R$)",
  "Mexican Peso ($)",
  "South African Rand (R)",
  "Singapore Dollar (S$)",
  "Hong Kong Dollar (HK$)",
  "New Zealand Dollar (NZ$)",
  "Swedish Krona (kr)",
  "Norwegian Krone (kr)",
  "Danish Krone (kr)",
  "Turkish Lira (₺)",
  "Indonesian Rupiah (Rp)",
  "Thai Baht (฿)",
  "Malaysian Ringgit (RM)",
  "Philippine Peso (₱)",
  "Pakistani Rupee (₨)",
  "Vietnamese Dong (₫)",
  "Saudi Riyal (ر.س)",
  "United Arab Emirates Dirham (د.إ)",
  "Egyptian Pound (£)",
  "Qatari Riyal (ر.ق)",
  "Kuwaiti Dinar (د.ك)",
  "Omani Rial (ر.ع.)",
  "Israeli Shekel (₪)",
  "Polish Zloty (zł)",
  "Czech Koruna (Kč)",
  "Hungarian Forint (Ft)",
  "Romanian Leu (L)",
  "Bulgarian Lev (лв.)",
  "Croatian Kuna (kn)",
  "Icelandic Krona (kr)",
  "Ukrainian Hryvnia (₴)",
  "Argentine Peso ($)",
  "Chilean Peso ($)",
  "Peruvian Sol (S/)",
  "Colombian Peso ($)",
  "Venezuelan Bolívar (Bs.)",
  "Ghanaian Cedi (₵)",
  "Nigerian Naira (₦)",
  "Kenyan Shilling (Sh)",
  "Tanzanian Shilling (Sh)",
  "Ugandan Shilling (Sh)",
  "Ethiopian Birr (Br)",
  "Moroccan Dirham (د.م.)",
  "Tunisian Dinar (د.ت)",
  "Jordanian Dinar (د.ا)",
  "Bahraini Dinar (ب.د)",
  "Sri Lankan Rupee (Rs)",
  "Bangladeshi Taka (৳)",
  "Nepalese Rupee (रू)",
  "Afghan Afghani (؋)",
  "Iranian Rial (﷼)",
  "Iraqi Dinar (د.ع)",
  "Lebanese Pound (ل.ل)",
  "Syrian Pound (£S)",
  "Myanmar Kyat (K)",
  "Cambodian Riel (៛)",
  "Laotian Kip (₭)",
  "Mongolian Tugrik (₮)",
  "Kazakhstani Tenge (₸)",
  "Uzbekistani Som (soʻm)",
  "Turkmenistan Manat (m)",
  "Georgian Lari (₾)",
  "Armenian Dram (֏)",
  "Azerbaijani Manat (₼)",
  "Belarusian Ruble (Br)",
  "Serbian Dinar (дин)",
  "Macedonian Denar (ден)",
  "Bosnia and Herzegovina Convertible Mark (KM)",
  "Albanian Lek (L)",
  "Moldovan Leu (L)",
  "Maldivian Rufiyaa (ރ.)",
  "Mauritian Rupee (Rs)",
  "Seychellois Rupee (₨)",
  "Fijian Dollar ($)",
  "Papua New Guinean Kina (K)",
  "Samoan Tala (T)",
  "Tongan Paʻanga (T$)",
  "Vanuatu Vatu (VT)",
  "Solomon Islands Dollar ($)",
  "East Caribbean Dollar (EC$)",
  "Barbadian Dollar ($)",
  "Bahamian Dollar ($)",
  "Jamaican Dollar (J$)",
  "Trinidad and Tobago Dollar (TT$)",
  "Haitian Gourde (G)",
  "Dominican Peso (RD$)",
  "Cuban Peso ($)",
  "Panamanian Balboa (B/.)",
  "Costa Rican Colón (₡)",
  "Honduran Lempira (L)",
  "Nicaraguan Córdoba (C$)",
  "Guatemalan Quetzal (Q)",
  "El Salvadoran Colón (₡)",
  "Belize Dollar (BZ$)",
];

export const currencyList = currencies.map((item) => ({
  value: item,
  label: item,
}));
