module.exports = {
  bracketSpacing: true,
  semi: true,
  arrowParens: "always",
  bracketSameLine: true,
  singleQuote: false,
  jsxSingleQuote: false,
  trailingComma: "es5",
  printWidth: 110,
  importOrder: [
    "^react$",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "^@referrer/(.*)$",
    "^@/components/(.*)$",
    "^@/lib/(.*)$",
    "^@/config/(.*)$",
    "^@/store/(.*)$",
    "^@/hooks/(.*)$",
    "^@/public/(.*)$",
    "^@/types/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  tailwindFunctions: ["clsx"],
  plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
};
